In [1]:
from langchain_community.document_loaders import TextLoader
from chunking import chunk_text


# --------------------------------------------------
# LOAD KNOWLEDGE BASE
# --------------------------------------------------

filename = "C:\\Users\\priya\\genai_classes_project\\DSA_coach_proj\\knowledge_base\\fivehundredwords_dsa.txt"

loader = TextLoader(filename, encoding="utf-8")
docs = loader.load()

text_content = docs[0].page_content


# --------------------------------------------------
# GENERATE CHUNKS USING ALL 3 METHODS
# --------------------------------------------------

chunks_dict = chunk_text(text_content)


# --------------------------------------------------
# EVALUATE CHUNKING METHODS
# --------------------------------------------------

print("\n" + "=" * 60)
print("           CHUNKING EVALUATION")
print("=" * 60)


for method, chunks in chunks_dict.items():

    print("\n" + "-" * 60)

    if method == "recursive":
        method_name = "RecursiveCharacterTextSplitter"

    elif method == "character":
        method_name = "CharacterTextSplitter"

    else:
        method_name = "TokenTextSplitter"

    print(f"Method: {method_name}")
    print("-" * 60)

    # Number of chunks
    number_of_chunks = len(chunks)

    # Character lengths
    chunk_lengths = [len(chunk) for chunk in chunks]

    average_length = sum(chunk_lengths) / len(chunk_lengths)

    minimum_length = min(chunk_lengths)
    maximum_length = max(chunk_lengths)

    total_characters = sum(chunk_lengths)

    print(f"Number of chunks:       {number_of_chunks}")
    print(f"Average chunk length:   {average_length:.2f} characters")
    print(f"Minimum chunk length:   {minimum_length} characters")
    print(f"Maximum chunk length:   {maximum_length} characters")
    print(f"Total characters:       {total_characters}")


print("\n" + "=" * 60)
print("Evaluation completed.")
print("=" * 60)

C:\Users\priya\AppData\Local\Temp\ipykernel_14516\2141914932.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import TextLoader
c:\Users\priya\genai_classes_project\DSA_coach_proj\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

🔹 RecursiveCharacterTextSplitter produced: 16 chunks
🔹 CharacterTextSplitter produced: 16 chunks
🔹 TokenTextSplitter produced: 6 chunks

============================================================
           CHUNKING EVALUATION
============================================================

------------------------------------------------------------
Method: RecursiveCharacterTextSplitter
------------------------------------------------------------
Number of chunks:       16
Average chunk length:   393.19 characters
Minimum chunk length:   316 characters
Maximum chunk length:   498 characters
Total characters:       6291

------------------------------------------------------------
Method: CharacterTextSplitter
------------------------------------------------------------
Number of chunks:       16
Average chunk length:   391.00 characters
Minimum chunk length:   315 characters
Maximum chunk length:   494 characters
Total characters:       6256

------------------------------------------------------------
Method: TokenTextSplitter
------------------------------------------------------------
Number of chunks:       6
Average chunk length:   1126.50 characters
Minimum chunk length:   1047 characters
Maximum chunk length:   1195 characters
Total characters:       6759

============================================================
Evaluation completed.
============================================================

In [8]:
import numpy as np
import pandas as pd
from langchain_community.document_loaders import TextLoader
from model import embeddings
from chunking import chunk_text

In [9]:
filename ="C:\\Users\\priya\\genai_classes_project\\DSA_coach_proj\\knowledge_base\\fivehundredwords_dsa.txt"

loader = TextLoader(filename, encoding="utf-8")
docs = loader.load()

text_content = docs[0].page_content

# Generate all three chunking strategies
chunks_dict = chunk_text(text_content)

print("Knowledge base loaded successfully.")
print(f"Total characters: {len(text_content)}")

🔹 RecursiveCharacterTextSplitter produced: 16 chunks
🔹 CharacterTextSplitter produced: 16 chunks
🔹 TokenTextSplitter produced: 6 chunks
Knowledge base loaded successfully.
Total characters: 6311

In [4]:
for method, chunks in chunks_dict.items():
    print("\n" + "=" * 70)
    print(f"{method.upper()} CHUNKS")
    print("=" * 70)

    for i, chunk in enumerate(chunks):
        print(f"\n--- Chunk {i + 1} ---")
        print(chunk[:500])

======================================================================
RECURSIVE CHUNKS
======================================================================

--- Chunk 1 ---
DSA FUNDAMENTALS KNOWLEDGE BASE

1. ARRAYS

An array is a linear data structure used to store multiple elements in a collection. In a traditional array, elements are stored in contiguous memory locations. Each element can be accessed using an index. Most programming languages use zero-based indexing, meaning the first element is at index 0.

--- Chunk 2 ---
For example, an array containing 10, 20, 30 and 40 has 10 at index 0, 20 at index 1, 30 at index 2 and 40 at index 3. Accessing an element using its index takes O(1) time.

Common operations on arrays include traversal, searching, insertion, deletion and updating. Searching an unsorted array generally takes O(n) time. Inserting or deleting an element from the middle may take O(n) time because other elements may need to be shifted.

--- Chunk 3 ---
Arrays are useful when fast random access is required. They are commonly used to implement other data structures such as stacks, heaps and dynamic arrays.

2. LINKED LIST

A linked list is a linear data structure made up of nodes. Each node contains data and a reference to another node. Unlike arrays, linked-list nodes do not have to be stored in contiguous memory locations.

--- Chunk 4 ---
A singly linked list contains a data field and a pointer to the next node. A doubly linked list contains pointers to both the previous and next nodes.

Searching for an element in a linked list takes O(n) time because nodes must generally be visited one by one. Insertion and deletion can be O(1) when the position or required node reference is already known.

--- Chunk 5 ---
Linked lists are useful when frequent insertion and deletion operations are required. However, they do not provide direct random access like arrays.

3. STACK

A stack is a linear data structure that follows the LIFO principle, which means Last In, First Out. The element inserted most recently is removed first.

The main stack operations are push, pop and peek. Push adds an element to the top of the stack. Pop removes the top element. Peek returns the top element without removing it.

--- Chunk 6 ---
Stack operations generally take O(1) time.

Stacks are commonly used in function calls, recursion, expression evaluation, undo operations and browser history. A stack can be implemented using an array or a linked list.

4. QUEUE

A queue is a linear data structure that follows the FIFO principle, which means First In, First Out. The element inserted first is removed first.

--- Chunk 7 ---
The main operations are enqueue and dequeue. Enqueue adds an element to the rear of the queue, while dequeue removes an element from the front.

Queues are commonly used in scheduling systems, printer queues, operating systems, breadth-first search and network processing.

A queue can be implemented using arrays, linked lists or specialized queue data structures.

5. BINARY SEARCH

Binary search is an efficient searching algorithm used to find an element in a sorted array or sorted collection.

--- Chunk 8 ---
The algorithm maintains two boundaries, usually called low and high. It calculates the middle position and compares the middle element with the target.

If the middle element is equal to the target, the search is successful. If the target is greater than the middle element, the left half can be discarded. If the target is smaller, the right half can be discarded.

--- Chunk 9 ---
The search space is divided approximately in half after every comparison. Therefore, binary search has O(log n) time complexity and O(1) auxiliary space for its iterative implementation.

Binary search requires the data to be sorted.

6. LINEAR SEARCH

Linear search is a simple searching algorithm that checks elements one by one until the target is found or the collection ends.

--- Chunk 10 ---
Linear search can work on both sorted and unsorted data. In the worst case, every element must be examined, giving it O(n) time complexity.

Linear search is useful for small collections or situations where the data is not sorted and sorting would not be worthwhile.

7. SORTING

Sorting means arranging data according to a particular order, usually ascending or descending.

Common sorting algorithms include bubble sort, selection sort, insertion sort, merge sort and quicksort.

--- Chunk 11 ---
Bubble sort repeatedly compares adjacent elements and swaps them when they are in the wrong order. Its average and worst-case time complexity is O(n²).

Merge sort uses divide and conquer. It divides the array into smaller parts, recursively sorts them and merges the sorted parts. Its time complexity is O(n log n).

--- Chunk 12 ---
Quicksort also uses divide and conquer. It selects a pivot and partitions the elements around the pivot. Its average time complexity is O(n log n), although its worst case can be O(n²).

8. RECURSION

Recursion is a programming technique in which a function calls itself to solve a smaller version of the same problem.

--- Chunk 13 ---
Every recursive solution should have a base case that stops further recursive calls. Without a proper base case, the program may continue calling the function until a stack overflow occurs.

Recursion is commonly used in tree traversal, graph algorithms, divide-and-conquer algorithms, factorial calculations and Fibonacci problems.

9. TREES

--- Chunk 14 ---
9. TREES

A tree is a hierarchical data structure consisting of nodes connected by edges. The top node is called the root. Nodes can have children, and nodes without children are called leaves.

A binary tree is a tree in which each node has at most two children. A binary search tree maintains an ordering where values smaller than a node are generally stored in its left subtree and larger values are stored in its right subtree.

--- Chunk 15 ---
Tree traversal techniques include preorder, inorder and postorder traversal. Breadth-first traversal can also be performed using a queue.

10. GRAPHS

A graph is a data structure consisting of vertices and edges. Graphs can represent relationships such as roads between cities, connections between users or links between web pages.

Graphs may be directed or undirected and may contain weighted or unweighted edges.

--- Chunk 16 ---
Two common graph traversal algorithms are Breadth-First Search and Depth-First Search. BFS explores nodes level by level and generally uses a queue. DFS explores as deeply as possible before backtracking and can use recursion or a stack.

BFS and DFS generally have O(V + E) time complexity, where V represents the number of vertices and E represents the number of edges.

======================================================================
CHARACTER CHUNKS
======================================================================

--- Chunk 1 ---
DSA FUNDAMENTALS KNOWLEDGE BASE
1. ARRAYS
An array is a linear data structure used to store multiple elements in a collection. In a traditional array, elements are stored in contiguous memory locations. Each element can be accessed using an index. Most programming languages use zero-based indexing, meaning the first element is at index 0.

--- Chunk 2 ---
For example, an array containing 10, 20, 30 and 40 has 10 at index 0, 20 at index 1, 30 at index 2 and 40 at index 3. Accessing an element using its index takes O(1) time.
Common operations on arrays include traversal, searching, insertion, deletion and updating. Searching an unsorted array generally takes O(n) time. Inserting or deleting an element from the middle may take O(n) time because other elements may need to be shifted.

--- Chunk 3 ---
Arrays are useful when fast random access is required. They are commonly used to implement other data structures such as stacks, heaps and dynamic arrays.
2. LINKED LIST
A linked list is a linear data structure made up of nodes. Each node contains data and a reference to another node. Unlike arrays, linked-list nodes do not have to be stored in contiguous memory locations.

--- Chunk 4 ---
A singly linked list contains a data field and a pointer to the next node. A doubly linked list contains pointers to both the previous and next nodes.
Searching for an element in a linked list takes O(n) time because nodes must generally be visited one by one. Insertion and deletion can be O(1) when the position or required node reference is already known.

--- Chunk 5 ---
Linked lists are useful when frequent insertion and deletion operations are required. However, they do not provide direct random access like arrays.
3. STACK
A stack is a linear data structure that follows the LIFO principle, which means Last In, First Out. The element inserted most recently is removed first.
The main stack operations are push, pop and peek. Push adds an element to the top of the stack. Pop removes the top element. Peek returns the top element without removing it.

--- Chunk 6 ---
Stack operations generally take O(1) time.
Stacks are commonly used in function calls, recursion, expression evaluation, undo operations and browser history. A stack can be implemented using an array or a linked list.
4. QUEUE
A queue is a linear data structure that follows the FIFO principle, which means First In, First Out. The element inserted first is removed first.

--- Chunk 7 ---
The main operations are enqueue and dequeue. Enqueue adds an element to the rear of the queue, while dequeue removes an element from the front.
Queues are commonly used in scheduling systems, printer queues, operating systems, breadth-first search and network processing.
A queue can be implemented using arrays, linked lists or specialized queue data structures.
5. BINARY SEARCH
Binary search is an efficient searching algorithm used to find an element in a sorted array or sorted collection.

--- Chunk 8 ---
The algorithm maintains two boundaries, usually called low and high. It calculates the middle position and compares the middle element with the target.
If the middle element is equal to the target, the search is successful. If the target is greater than the middle element, the left half can be discarded. If the target is smaller, the right half can be discarded.

--- Chunk 9 ---
The search space is divided approximately in half after every comparison. Therefore, binary search has O(log n) time complexity and O(1) auxiliary space for its iterative implementation.
Binary search requires the data to be sorted.
6. LINEAR SEARCH
Linear search is a simple searching algorithm that checks elements one by one until the target is found or the collection ends.

--- Chunk 10 ---
Linear search can work on both sorted and unsorted data. In the worst case, every element must be examined, giving it O(n) time complexity.
Linear search is useful for small collections or situations where the data is not sorted and sorting would not be worthwhile.
7. SORTING
Sorting means arranging data according to a particular order, usually ascending or descending.
Common sorting algorithms include bubble sort, selection sort, insertion sort, merge sort and quicksort.

--- Chunk 11 ---
Bubble sort repeatedly compares adjacent elements and swaps them when they are in the wrong order. Its average and worst-case time complexity is O(n²).
Merge sort uses divide and conquer. It divides the array into smaller parts, recursively sorts them and merges the sorted parts. Its time complexity is O(n log n).

--- Chunk 12 ---
Quicksort also uses divide and conquer. It selects a pivot and partitions the elements around the pivot. Its average time complexity is O(n log n), although its worst case can be O(n²).
8. RECURSION
Recursion is a programming technique in which a function calls itself to solve a smaller version of the same problem.

--- Chunk 13 ---
Every recursive solution should have a base case that stops further recursive calls. Without a proper base case, the program may continue calling the function until a stack overflow occurs.
Recursion is commonly used in tree traversal, graph algorithms, divide-and-conquer algorithms, factorial calculations and Fibonacci problems.
9. TREES

--- Chunk 14 ---
9. TREES
A tree is a hierarchical data structure consisting of nodes connected by edges. The top node is called the root. Nodes can have children, and nodes without children are called leaves.
A binary tree is a tree in which each node has at most two children. A binary search tree maintains an ordering where values smaller than a node are generally stored in its left subtree and larger values are stored in its right subtree.

--- Chunk 15 ---
Tree traversal techniques include preorder, inorder and postorder traversal. Breadth-first traversal can also be performed using a queue.
10. GRAPHS
A graph is a data structure consisting of vertices and edges. Graphs can represent relationships such as roads between cities, connections between users or links between web pages.
Graphs may be directed or undirected and may contain weighted or unweighted edges.

--- Chunk 16 ---
Two common graph traversal algorithms are Breadth-First Search and Depth-First Search. BFS explores nodes level by level and generally uses a queue. DFS explores as deeply as possible before backtracking and can use recursion or a stack.
BFS and DFS generally have O(V + E) time complexity, where V represents the number of vertices and E represents the number of edges.

======================================================================
TOKEN CHUNKS
======================================================================

--- Chunk 1 ---
DSA FUNDAMENTALS KNOWLEDGE BASE

1. ARRAYS

An array is a linear data structure used to store multiple elements in a collection. In a traditional array, elements are stored in contiguous memory locations. Each element can be accessed using an index. Most programming languages use zero-based indexing, meaning the first element is at index 0.

For example, an array containing 10, 20, 30 and 40 has 10 at index 0, 20 at index 1, 30 at index 2 and 40 at index 3. Accessing an element using its index t

--- Chunk 2 ---
 nodes. Each node contains data and a reference to another node. Unlike arrays, linked-list nodes do not have to be stored in contiguous memory locations.

A singly linked list contains a data field and a pointer to the next node. A doubly linked list contains pointers to both the previous and next nodes.

Searching for an element in a linked list takes O(n) time because nodes must generally be visited one by one. Insertion and deletion can be O(1) when the position or required node reference is

--- Chunk 3 ---
acks are commonly used in function calls, recursion, expression evaluation, undo operations and browser history. A stack can be implemented using an array or a linked list.

4. QUEUE

A queue is a linear data structure that follows the FIFO principle, which means First In, First Out. The element inserted first is removed first.

The main operations are enqueue and dequeue. Enqueue adds an element to the rear of the queue, while dequeue removes an element from the front.

Queues are commonly used

--- Chunk 4 ---
, the left half can be discarded. If the target is smaller, the right half can be discarded.

The search space is divided approximately in half after every comparison. Therefore, binary search has O(log n) time complexity and O(1) auxiliary space for its iterative implementation.

Binary search requires the data to be sorted.

6. LINEAR SEARCH

Linear search is a simple searching algorithm that checks elements one by one until the target is found or the collection ends.

Linear search can work o

--- Chunk 5 ---
 and worst-case time complexity is O(n²).

Merge sort uses divide and conquer. It divides the array into smaller parts, recursively sorts them and merges the sorted parts. Its time complexity is O(n log n).

Quicksort also uses divide and conquer. It selects a pivot and partitions the elements around the pivot. Its average time complexity is O(n log n), although its worst case can be O(n²).

8. RECURSION

Recursion is a programming technique in which a function calls itself to solve a smaller ve

--- Chunk 6 ---
 are called leaves.

A binary tree is a tree in which each node has at most two children. A binary search tree maintains an ordering where values smaller than a node are generally stored in its left subtree and larger values are stored in its right subtree.

Tree traversal techniques include preorder, inorder and postorder traversal. Breadth-first traversal can also be performed using a queue.

10. GRAPHS

A graph is a data structure consisting of vertices and edges. Graphs can represent relatio

In [10]:
evaluation_questions = [
    "What is an array?",
    "What is a linked list?",
    "What is a stack?",
    "What is a queue?",
    "What is binary search?",
    "What is the time complexity of binary search?",
    "What is a tree?",
    "What is a binary tree?",
    "What is a graph?",
    "What is the difference between an array and a linked list?"
]

print(f"Number of evaluation questions: {len(evaluation_questions)}")

Number of evaluation questions: 10

In [11]:
# ============================================================
# CREATE EMBEDDINGS FOR ALL CHUNKING METHODS
# ============================================================

chunk_embeddings = {}

for method, chunks in chunks_dict.items():

    print(f"\nCreating embeddings for: {method}")

    vectors = []

    for i, chunk in enumerate(chunks):

        vector = embeddings.embed_query(chunk)
        vectors.append(np.array(vector))

    chunk_embeddings[method] = np.array(vectors)

    print(
        f"{method}: "
        f"{len(vectors)} embeddings created"
    )

Creating embeddings for: recursive
recursive: 16 embeddings created

Creating embeddings for: character
character: 16 embeddings created

Creating embeddings for: token
token: 6 embeddings created

In [12]:
# ============================================================
# RETRIEVAL FUNCTION
# ============================================================

def retrieve_top_k(query, chunks, vectors, top_k=5):

    query_vector = np.array(
        embeddings.embed_query(query)
    )

    query_norm = np.linalg.norm(query_vector)

    scores = []

    for i, vector in enumerate(vectors):

        vector_norm = np.linalg.norm(vector)

        similarity = np.dot(
            query_vector,
            vector
        ) / (
            query_norm * vector_norm
        )

        scores.append({
            "chunk_id": i,
            "score": float(similarity),
            "content": chunks[i]
        })

    scores.sort(
        key=lambda x: x["score"],
        reverse=True
    )

    return scores[:top_k]

In [13]:
# ============================================================
# RUN RETRIEVAL FOR ALL QUESTIONS
# ============================================================

retrieval_results = []

for question in evaluation_questions:

    for method in chunks_dict:

        results = retrieve_top_k(
            question,
            chunks_dict[method],
            chunk_embeddings[method],
            top_k=5
        )

        for rank, result in enumerate(results, start=1):

            retrieval_results.append({
                "question": question,
                "method": method,
                "rank": rank,
                "chunk_id": result["chunk_id"],
                "score": result["score"]
            })

retrieval_df = pd.DataFrame(retrieval_results)

retrieval_df.head(20)

                  question     method  rank  chunk_id     score
0        What is an array?  recursive     1         0  0.686999
1        What is an array?  recursive     2         1  0.656812
2        What is an array?  recursive     3         2  0.642147
3        What is an array?  recursive     4         6  0.627923
4        What is an array?  recursive     5         5  0.612902
5        What is an array?  character     1         0  0.687894
6        What is an array?  character     2         1  0.659191
7        What is an array?  character     3         2  0.647399
8        What is an array?  character     4         6  0.627380
9        What is an array?  character     5         5  0.617402
10       What is an array?      token     1         0  0.642914
11       What is an array?      token     2         1  0.635553
12       What is an array?      token     3         2  0.625069
13       What is an array?      token     4         4  0.596257
14       What is an array?      token     5         5  0.595925
15  What is a linked list?  recursive     1         3  0.699369
16  What is a linked list?  recursive     2         2  0.694408
17  What is a linked list?  recursive     3         4  0.659002
18  What is a linked list?  recursive     4         5  0.655678
19  What is a linked list?  recursive     5         6  0.628855

In [14]:
for method, chunks in chunks_dict.items():

    print("\n" + "=" * 80)
    print(f"{method.upper()} — CHUNKS")
    print("=" * 80)

    for i, chunk in enumerate(chunks):
        print(f"\n--- CHUNK {i} ---")
        print(chunk)

================================================================================
RECURSIVE — CHUNKS
================================================================================

--- CHUNK 0 ---
DSA FUNDAMENTALS KNOWLEDGE BASE

1. ARRAYS

An array is a linear data structure used to store multiple elements in a collection. In a traditional array, elements are stored in contiguous memory locations. Each element can be accessed using an index. Most programming languages use zero-based indexing, meaning the first element is at index 0.

--- CHUNK 1 ---
For example, an array containing 10, 20, 30 and 40 has 10 at index 0, 20 at index 1, 30 at index 2 and 40 at index 3. Accessing an element using its index takes O(1) time.

Common operations on arrays include traversal, searching, insertion, deletion and updating. Searching an unsorted array generally takes O(n) time. Inserting or deleting an element from the middle may take O(n) time because other elements may need to be shifted.

--- CHUNK 2 ---
Arrays are useful when fast random access is required. They are commonly used to implement other data structures such as stacks, heaps and dynamic arrays.

2. LINKED LIST

A linked list is a linear data structure made up of nodes. Each node contains data and a reference to another node. Unlike arrays, linked-list nodes do not have to be stored in contiguous memory locations.

--- CHUNK 3 ---
A singly linked list contains a data field and a pointer to the next node. A doubly linked list contains pointers to both the previous and next nodes.

Searching for an element in a linked list takes O(n) time because nodes must generally be visited one by one. Insertion and deletion can be O(1) when the position or required node reference is already known.

--- CHUNK 4 ---
Linked lists are useful when frequent insertion and deletion operations are required. However, they do not provide direct random access like arrays.

3. STACK

A stack is a linear data structure that follows the LIFO principle, which means Last In, First Out. The element inserted most recently is removed first.

The main stack operations are push, pop and peek. Push adds an element to the top of the stack. Pop removes the top element. Peek returns the top element without removing it.

--- CHUNK 5 ---
Stack operations generally take O(1) time.

Stacks are commonly used in function calls, recursion, expression evaluation, undo operations and browser history. A stack can be implemented using an array or a linked list.

4. QUEUE

A queue is a linear data structure that follows the FIFO principle, which means First In, First Out. The element inserted first is removed first.

--- CHUNK 6 ---
The main operations are enqueue and dequeue. Enqueue adds an element to the rear of the queue, while dequeue removes an element from the front.

Queues are commonly used in scheduling systems, printer queues, operating systems, breadth-first search and network processing.

A queue can be implemented using arrays, linked lists or specialized queue data structures.

5. BINARY SEARCH

Binary search is an efficient searching algorithm used to find an element in a sorted array or sorted collection.

--- CHUNK 7 ---
The algorithm maintains two boundaries, usually called low and high. It calculates the middle position and compares the middle element with the target.

If the middle element is equal to the target, the search is successful. If the target is greater than the middle element, the left half can be discarded. If the target is smaller, the right half can be discarded.

--- CHUNK 8 ---
The search space is divided approximately in half after every comparison. Therefore, binary search has O(log n) time complexity and O(1) auxiliary space for its iterative implementation.

Binary search requires the data to be sorted.

6. LINEAR SEARCH

Linear search is a simple searching algorithm that checks elements one by one until the target is found or the collection ends.

--- CHUNK 9 ---
Linear search can work on both sorted and unsorted data. In the worst case, every element must be examined, giving it O(n) time complexity.

Linear search is useful for small collections or situations where the data is not sorted and sorting would not be worthwhile.

7. SORTING

Sorting means arranging data according to a particular order, usually ascending or descending.

Common sorting algorithms include bubble sort, selection sort, insertion sort, merge sort and quicksort.

--- CHUNK 10 ---
Bubble sort repeatedly compares adjacent elements and swaps them when they are in the wrong order. Its average and worst-case time complexity is O(n²).

Merge sort uses divide and conquer. It divides the array into smaller parts, recursively sorts them and merges the sorted parts. Its time complexity is O(n log n).

--- CHUNK 11 ---
Quicksort also uses divide and conquer. It selects a pivot and partitions the elements around the pivot. Its average time complexity is O(n log n), although its worst case can be O(n²).

8. RECURSION

Recursion is a programming technique in which a function calls itself to solve a smaller version of the same problem.

--- CHUNK 12 ---
Every recursive solution should have a base case that stops further recursive calls. Without a proper base case, the program may continue calling the function until a stack overflow occurs.

Recursion is commonly used in tree traversal, graph algorithms, divide-and-conquer algorithms, factorial calculations and Fibonacci problems.

9. TREES

--- CHUNK 13 ---
9. TREES

A tree is a hierarchical data structure consisting of nodes connected by edges. The top node is called the root. Nodes can have children, and nodes without children are called leaves.

A binary tree is a tree in which each node has at most two children. A binary search tree maintains an ordering where values smaller than a node are generally stored in its left subtree and larger values are stored in its right subtree.

--- CHUNK 14 ---
Tree traversal techniques include preorder, inorder and postorder traversal. Breadth-first traversal can also be performed using a queue.

10. GRAPHS

A graph is a data structure consisting of vertices and edges. Graphs can represent relationships such as roads between cities, connections between users or links between web pages.

Graphs may be directed or undirected and may contain weighted or unweighted edges.

--- CHUNK 15 ---
Two common graph traversal algorithms are Breadth-First Search and Depth-First Search. BFS explores nodes level by level and generally uses a queue. DFS explores as deeply as possible before backtracking and can use recursion or a stack.

BFS and DFS generally have O(V + E) time complexity, where V represents the number of vertices and E represents the number of edges.

================================================================================
CHARACTER — CHUNKS
================================================================================

--- CHUNK 0 ---
DSA FUNDAMENTALS KNOWLEDGE BASE
1. ARRAYS
An array is a linear data structure used to store multiple elements in a collection. In a traditional array, elements are stored in contiguous memory locations. Each element can be accessed using an index. Most programming languages use zero-based indexing, meaning the first element is at index 0.

--- CHUNK 1 ---
For example, an array containing 10, 20, 30 and 40 has 10 at index 0, 20 at index 1, 30 at index 2 and 40 at index 3. Accessing an element using its index takes O(1) time.
Common operations on arrays include traversal, searching, insertion, deletion and updating. Searching an unsorted array generally takes O(n) time. Inserting or deleting an element from the middle may take O(n) time because other elements may need to be shifted.

--- CHUNK 2 ---
Arrays are useful when fast random access is required. They are commonly used to implement other data structures such as stacks, heaps and dynamic arrays.
2. LINKED LIST
A linked list is a linear data structure made up of nodes. Each node contains data and a reference to another node. Unlike arrays, linked-list nodes do not have to be stored in contiguous memory locations.

--- CHUNK 3 ---
A singly linked list contains a data field and a pointer to the next node. A doubly linked list contains pointers to both the previous and next nodes.
Searching for an element in a linked list takes O(n) time because nodes must generally be visited one by one. Insertion and deletion can be O(1) when the position or required node reference is already known.

--- CHUNK 4 ---
Linked lists are useful when frequent insertion and deletion operations are required. However, they do not provide direct random access like arrays.
3. STACK
A stack is a linear data structure that follows the LIFO principle, which means Last In, First Out. The element inserted most recently is removed first.
The main stack operations are push, pop and peek. Push adds an element to the top of the stack. Pop removes the top element. Peek returns the top element without removing it.

--- CHUNK 5 ---
Stack operations generally take O(1) time.
Stacks are commonly used in function calls, recursion, expression evaluation, undo operations and browser history. A stack can be implemented using an array or a linked list.
4. QUEUE
A queue is a linear data structure that follows the FIFO principle, which means First In, First Out. The element inserted first is removed first.

--- CHUNK 6 ---
The main operations are enqueue and dequeue. Enqueue adds an element to the rear of the queue, while dequeue removes an element from the front.
Queues are commonly used in scheduling systems, printer queues, operating systems, breadth-first search and network processing.
A queue can be implemented using arrays, linked lists or specialized queue data structures.
5. BINARY SEARCH
Binary search is an efficient searching algorithm used to find an element in a sorted array or sorted collection.

--- CHUNK 7 ---
The algorithm maintains two boundaries, usually called low and high. It calculates the middle position and compares the middle element with the target.
If the middle element is equal to the target, the search is successful. If the target is greater than the middle element, the left half can be discarded. If the target is smaller, the right half can be discarded.

--- CHUNK 8 ---
The search space is divided approximately in half after every comparison. Therefore, binary search has O(log n) time complexity and O(1) auxiliary space for its iterative implementation.
Binary search requires the data to be sorted.
6. LINEAR SEARCH
Linear search is a simple searching algorithm that checks elements one by one until the target is found or the collection ends.

--- CHUNK 9 ---
Linear search can work on both sorted and unsorted data. In the worst case, every element must be examined, giving it O(n) time complexity.
Linear search is useful for small collections or situations where the data is not sorted and sorting would not be worthwhile.
7. SORTING
Sorting means arranging data according to a particular order, usually ascending or descending.
Common sorting algorithms include bubble sort, selection sort, insertion sort, merge sort and quicksort.

--- CHUNK 10 ---
Bubble sort repeatedly compares adjacent elements and swaps them when they are in the wrong order. Its average and worst-case time complexity is O(n²).
Merge sort uses divide and conquer. It divides the array into smaller parts, recursively sorts them and merges the sorted parts. Its time complexity is O(n log n).

--- CHUNK 11 ---
Quicksort also uses divide and conquer. It selects a pivot and partitions the elements around the pivot. Its average time complexity is O(n log n), although its worst case can be O(n²).
8. RECURSION
Recursion is a programming technique in which a function calls itself to solve a smaller version of the same problem.

--- CHUNK 12 ---
Every recursive solution should have a base case that stops further recursive calls. Without a proper base case, the program may continue calling the function until a stack overflow occurs.
Recursion is commonly used in tree traversal, graph algorithms, divide-and-conquer algorithms, factorial calculations and Fibonacci problems.
9. TREES

--- CHUNK 13 ---
9. TREES
A tree is a hierarchical data structure consisting of nodes connected by edges. The top node is called the root. Nodes can have children, and nodes without children are called leaves.
A binary tree is a tree in which each node has at most two children. A binary search tree maintains an ordering where values smaller than a node are generally stored in its left subtree and larger values are stored in its right subtree.

--- CHUNK 14 ---
Tree traversal techniques include preorder, inorder and postorder traversal. Breadth-first traversal can also be performed using a queue.
10. GRAPHS
A graph is a data structure consisting of vertices and edges. Graphs can represent relationships such as roads between cities, connections between users or links between web pages.
Graphs may be directed or undirected and may contain weighted or unweighted edges.

--- CHUNK 15 ---
Two common graph traversal algorithms are Breadth-First Search and Depth-First Search. BFS explores nodes level by level and generally uses a queue. DFS explores as deeply as possible before backtracking and can use recursion or a stack.
BFS and DFS generally have O(V + E) time complexity, where V represents the number of vertices and E represents the number of edges.

================================================================================
TOKEN — CHUNKS
================================================================================

--- CHUNK 0 ---
DSA FUNDAMENTALS KNOWLEDGE BASE

1. ARRAYS

An array is a linear data structure used to store multiple elements in a collection. In a traditional array, elements are stored in contiguous memory locations. Each element can be accessed using an index. Most programming languages use zero-based indexing, meaning the first element is at index 0.

For example, an array containing 10, 20, 30 and 40 has 10 at index 0, 20 at index 1, 30 at index 2 and 40 at index 3. Accessing an element using its index takes O(1) time.

Common operations on arrays include traversal, searching, insertion, deletion and updating. Searching an unsorted array generally takes O(n) time. Inserting or deleting an element from the middle may take O(n) time because other elements may need to be shifted.

Arrays are useful when fast random access is required. They are commonly used to implement other data structures such as stacks, heaps and dynamic arrays.

2. LINKED LIST

A linked list is a linear data structure made up of nodes. Each node contains data and a reference to another node. Unlike arrays, linked-list nodes

--- CHUNK 1 ---
 nodes. Each node contains data and a reference to another node. Unlike arrays, linked-list nodes do not have to be stored in contiguous memory locations.

A singly linked list contains a data field and a pointer to the next node. A doubly linked list contains pointers to both the previous and next nodes.

Searching for an element in a linked list takes O(n) time because nodes must generally be visited one by one. Insertion and deletion can be O(1) when the position or required node reference is already known.

Linked lists are useful when frequent insertion and deletion operations are required. However, they do not provide direct random access like arrays.

3. STACK

A stack is a linear data structure that follows the LIFO principle, which means Last In, First Out. The element inserted most recently is removed first.

The main stack operations are push, pop and peek. Push adds an element to the top of the stack. Pop removes the top element. Peek returns the top element without removing it.

Stack operations generally take O(1) time.

Stacks are commonly used in function calls, recursion, expression evaluation, undo operations and browser history.

--- CHUNK 2 ---
acks are commonly used in function calls, recursion, expression evaluation, undo operations and browser history. A stack can be implemented using an array or a linked list.

4. QUEUE

A queue is a linear data structure that follows the FIFO principle, which means First In, First Out. The element inserted first is removed first.

The main operations are enqueue and dequeue. Enqueue adds an element to the rear of the queue, while dequeue removes an element from the front.

Queues are commonly used in scheduling systems, printer queues, operating systems, breadth-first search and network processing.

A queue can be implemented using arrays, linked lists or specialized queue data structures.

5. BINARY SEARCH

Binary search is an efficient searching algorithm used to find an element in a sorted array or sorted collection.

The algorithm maintains two boundaries, usually called low and high. It calculates the middle position and compares the middle element with the target.

If the middle element is equal to the target, the search is successful. If the target is greater than the middle element, the left half can be discarded. If the target is smaller, the right half can be discarded

--- CHUNK 3 ---
, the left half can be discarded. If the target is smaller, the right half can be discarded.

The search space is divided approximately in half after every comparison. Therefore, binary search has O(log n) time complexity and O(1) auxiliary space for its iterative implementation.

Binary search requires the data to be sorted.

6. LINEAR SEARCH

Linear search is a simple searching algorithm that checks elements one by one until the target is found or the collection ends.

Linear search can work on both sorted and unsorted data. In the worst case, every element must be examined, giving it O(n) time complexity.

Linear search is useful for small collections or situations where the data is not sorted and sorting would not be worthwhile.

7. SORTING

Sorting means arranging data according to a particular order, usually ascending or descending.

Common sorting algorithms include bubble sort, selection sort, insertion sort, merge sort and quicksort.

Bubble sort repeatedly compares adjacent elements and swaps them when they are in the wrong order. Its average and worst-case time complexity is O(n²).

Merge sort uses divide and

--- CHUNK 4 ---
 and worst-case time complexity is O(n²).

Merge sort uses divide and conquer. It divides the array into smaller parts, recursively sorts them and merges the sorted parts. Its time complexity is O(n log n).

Quicksort also uses divide and conquer. It selects a pivot and partitions the elements around the pivot. Its average time complexity is O(n log n), although its worst case can be O(n²).

8. RECURSION

Recursion is a programming technique in which a function calls itself to solve a smaller version of the same problem.

Every recursive solution should have a base case that stops further recursive calls. Without a proper base case, the program may continue calling the function until a stack overflow occurs.

Recursion is commonly used in tree traversal, graph algorithms, divide-and-conquer algorithms, factorial calculations and Fibonacci problems.

9. TREES

A tree is a hierarchical data structure consisting of nodes connected by edges. The top node is called the root. Nodes can have children, and nodes without children are called leaves.

A binary tree is a tree in which each node has at most two

--- CHUNK 5 ---
 are called leaves.

A binary tree is a tree in which each node has at most two children. A binary search tree maintains an ordering where values smaller than a node are generally stored in its left subtree and larger values are stored in its right subtree.

Tree traversal techniques include preorder, inorder and postorder traversal. Breadth-first traversal can also be performed using a queue.

10. GRAPHS


In [15]:
ground_truth = {
    "What is an array?": {
        "recursive": [0],
        "character": [0],
        "token": [0]
    },

    "What is a linked list?": {
        "recursive": [2],
        "character": [2],
        "token": [0, 1]
    },

    "What is a stack?": {
        "recursive": [4],
        "character": [4],
        "token": [1, 2]
    },

    "What is a queue?": {
        "recursive": [5],
        "character": [5],
        "token": [2]
    },

    "What is binary search?": {
        "recursive": [6, 7],
        "character": [6, 7],
        "token": [2, 3]
    },

    "What is the time complexity of binary search?": {
        "recursive": [8],
        "character": [8],
        "token": [3]
    },

    "What is a tree?": {
        "recursive": [13],
        "character": [13],
        "token": [4, 5]
    },

    "What is a binary tree?": {
        "recursive": [13],
        "character": [13],
        "token": [4, 5]
    },

    "What is a graph?": {
        "recursive": [14],
        "character": [14],
        "token": [5]
    },

    "What is the difference between an array and a linked list?": {
        "recursive": [0, 2, 4],
        "character": [0, 2, 4],
        "token": [0, 1, 2]
    }
}

In [16]:
def calculate_metrics(
    evaluation_questions,
    chunks_dict,
    chunk_embeddings,
    ground_truth,
    k_values=(1, 3, 5)
):
    metrics = []

    for method in chunks_dict:

        for k in k_values:

            hits = 0
            reciprocal_ranks = []

            for question in evaluation_questions:

                expected_chunks = set(
                    ground_truth[question][method]
                )

                results = retrieve_top_k(
                    question,
                    chunks_dict[method],
                    chunk_embeddings[method],
                    top_k=k
                )

                retrieved_ids = [
                    r["chunk_id"]
                    for r in results
                ]

                # -------------------------
                # Recall@K
                # -------------------------

                if expected_chunks.intersection(retrieved_ids):
                    hits += 1

                # -------------------------
                # MRR
                # -------------------------

                rank_found = None

                for rank, chunk_id in enumerate(
                    retrieved_ids,
                    start=1
                ):
                    if chunk_id in expected_chunks:
                        rank_found = rank
                        break

                if rank_found is not None:
                    reciprocal_ranks.append(
                        1 / rank_found
                    )
                else:
                    reciprocal_ranks.append(0)

            total = len(evaluation_questions)

            recall = hits / total

            mrr = np.mean(reciprocal_ranks)

            metrics.append({
                "Method": method,
                "K": k,
                "Recall@K": recall,
                "MRR": mrr
            })

    return pd.DataFrame(metrics)

In [17]:
metrics_df = calculate_metrics(
    evaluation_questions,
    chunks_dict,
    chunk_embeddings,
    ground_truth
)

metrics_df

      Method  K  Recall@K   MRR
0  recursive  1       0.8  0.80
1  recursive  3       1.0  0.90
2  recursive  5       1.0  0.90
3  character  1       0.9  0.90
4  character  3       1.0  0.95
5  character  5       1.0  0.95
6      token  1       1.0  1.00
7      token  3       1.0  1.00
8      token  5       1.0  1.00